---

dependencies:

  - role: debops.secret

galaxy_info:

  role_name: 'glusterfs_server'
  author: 'Julien Peeters'
  description: 'Install and manage Gluster cluster'
  company: 'Monkey Codex SAS'
  license: 'GPL-3.0'
  min_ansible_version: '2.5.0'
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - storage
    - sds
    - glusterfs
